/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cita;
import Modelo.Paciente;
import Modelo.Sistema;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 */
public class AsignacionCita extends javax.swing.JPanel {
    
    public static Sistema sistema = Vista.VentanaHome.Sistema_principal;
    private Paciente paciente;
    private ArrayList<Cita> citasDisponibles;

    /**
     * Creates new form AsignacionCita
     * @param paciente
     */
    public AsignacionCita(Paciente paciente) {
        initComponents();
        citasDisponibles = new ArrayList<>();
        this.paciente = paciente;
        
        DefaultTableModel model = (DefaultTableModel) citasTable.getModel();
        for(Cita c : sistema.getCitas()){
            if(c.getPaciente() == null){
                String fecha = CitasPaciente.getTextoFecha(c.getFecha());
                String especialidad = c.getEspecialidad();
                String medico = c.getMedico().getNombre();
                String lugar = c.getConsultorio().getSede();
                citasDisponibles.add(c);
                model.addRow(new Object[]{fecha, especialidad, medico, lugar});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPanel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        citasTable = new javax.swing.JTable();
        labelInstr = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        detallesButton = new javax.swing.JButton();
        RegistrarseButton = new javax.swing.JButton();

        labelPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPanel.setText("Citas médicas disponibles");

        citasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Especialidad", "Médico", "Lugar"
            }
        ));
        jScrollPane1.setViewportView(citasTable);

        labelInstr.setText("Seleccione la cita en la cual desea registrarse");

        detallesButton.setText("Detalles");
        detallesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallesButtonActionPerformed(evt);
            }
        });

        RegistrarseButton.setText("Registrarse");
        RegistrarseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(detallesButton)
                .addGap(130, 130, 130)
                .addComponent(RegistrarseButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detallesButton)
                    .addComponent(RegistrarseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInstr)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelPanel)
                .addGap(18, 18, 18)
                .addComponent(labelInstr)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseButtonActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
        int seleccion = citasTable.getSelectedRow();
        if(seleccion != -1){
            for(Cita c : sistema.getCitas()){
                if(c.equals(citasDisponibles.get(seleccion))){
                    c.setPaciente(paciente);
                    paciente.getCitasRegistradas().add(c);
                    int modelIndex = citasTable.convertRowIndexToModel(seleccion);
                    DefaultTableModel model = (DefaultTableModel) citasTable.getModel();
                    model.removeRow(modelIndex);
                    citasDisponibles.remove(seleccion);
                    break;
                }
            }
            JOptionPane.showMessageDialog(null, "Ha sido registrado en la cita");
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione una cita");
        }
    }//GEN-LAST:event_RegistrarseButtonActionPerformed

    private void detallesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallesButtonActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
        int seleccion = citasTable.getSelectedRow();
        if(seleccion != -1){
            Cita cita = this.citasDisponibles.get(seleccion);
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            String fecha = "Fecha: " + formato.format(cita.getFecha().getTime()) + "\n";
            String medico = "Medico: " + cita.getMedico().getNombre() + "\n";
            String especialidad = "Especialidad: " + cita.getEspecialidad() + "\n";
            String consultorio = "Lugar: Consultorio " + cita.getConsultorio().getNumero() + ", sede " + cita.getConsultorio().getSede() + "\n";
            JOptionPane.showMessageDialog(null, fecha + medico + especialidad + consultorio);
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione una cita");
        }
    }//GEN-LAST:event_detallesButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrarseButton;
    private javax.swing.JTable citasTable;
    private javax.swing.JButton detallesButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInstr;
    private javax.swing.JLabel labelPanel;
    // End of variables declaration//GEN-END:variables
}
