/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Administrador;
import Modelo.Mensaje;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Jorge
 */
public class CanalContactoMedico extends javax.swing.JPanel {
    
    private EnviarMensaje panelRespuesta;
    private final ArrayList<Mensaje> mensajesRecibidos;
    private int seleccion = -1;
    private boolean redactar = false;
    private String prevInfo = "";

    /**
     * Creates new form CanalContactoMedico
     */
    public CanalContactoMedico() {
        initComponents();
        this.remitenteTF.setEditable(false);
        this.fechaTF.setEditable(false);
        this.mensajeTA.setEditable(false);
        this.panelRespuesta = new EnviarMensaje(Login.med.getIdentificacion());
        this.panelRespuesta.setPanelMedico(this);
        this.panelRespuesta.setBackground(this.panelMensaje.getBackground());
        this.mensajesRecibidos = new ArrayList<>();
        
        for(Mensaje msg: VentanaHome.Sistema_principal.getMensajesParaMed()){
            if(msg.getIdDestinatario() == Login.med.getIdentificacion()){
                this.mensajesRecibidos.add(msg);
            }
            //System.out.println(msg.getIdDestinatario());
        }
        
        String[] model = new String[this.mensajesRecibidos.size()];
        
        for(int i = 0; i < this.mensajesRecibidos.size(); i++){
            model[i] = Long.toString(this.mensajesRecibidos.get(i).getIdRemitente());
        }
        
        this.listaMensajes.setListData(model);
        
        this.listaMensajes.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(remitenteLabel.getText().equals("Remitente:")){
                    seleccion = listaMensajes.getSelectedIndex();
                    Mensaje msg = mensajesRecibidos.get(seleccion);
                    long idRemitente = msg.getIdRemitente();
                    String nombreRemitente = "";
                    Calendar fecha = msg.getFecha();
                    String mensaje = msg.getMensaje();
                    for(Administrador ad: VentanaHome.Sistema_principal.getAdministradores()){
                        if(idRemitente == ad.getIdentificacion()){
                            nombreRemitente = ad.getNombre();
                            break;
                        }
                    }
                    prevInfo = nombreRemitente;
                    remitenteTF.setText(nombreRemitente);
                    fechaTF.setText(CitasPaciente.getTextoFecha(fecha));
                    mensajeTA.setText(mensaje);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        panelLabel = new javax.swing.JLabel();
        panelLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMensajes = new javax.swing.JList<>();
        panelContenido = new javax.swing.JPanel();
        panelRemitente = new javax.swing.JPanel();
        remitenteLabel = new javax.swing.JLabel();
        remitenteTF = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        fechaTF = new javax.swing.JTextField();
        panelMensaje = new javax.swing.JPanel();
        mensajeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mensajeTA = new javax.swing.JTextArea();
        redactarBtn = new javax.swing.JButton();
        responderBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));

        panelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelLabel.setText("Mensajes recibidos del administrador");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaMensajes.setBackground(new java.awt.Color(255, 204, 204));
        listaMensajes.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        listaMensajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaMensajes.setSelectionBackground(new java.awt.Color(255, 51, 51));
        jScrollPane1.setViewportView(listaMensajes);

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        panelContenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        remitenteLabel.setText("Remitente:");

        fechaLabel.setText("Fecha:");

        javax.swing.GroupLayout panelRemitenteLayout = new javax.swing.GroupLayout(panelRemitente);
        panelRemitente.setLayout(panelRemitenteLayout);
        panelRemitenteLayout.setHorizontalGroup(
            panelRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemitenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(remitenteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remitenteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fechaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaTF)
                .addContainerGap())
        );
        panelRemitenteLayout.setVerticalGroup(
            panelRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRemitenteLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(panelRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remitenteLabel)
                    .addComponent(remitenteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaLabel)
                    .addComponent(fechaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelMensaje.setBackground(new java.awt.Color(255, 204, 204));

        mensajeLabel.setText("Mensaje:");

        mensajeTA.setBackground(new java.awt.Color(255, 204, 204));
        mensajeTA.setColumns(20);
        mensajeTA.setRows(5);
        jScrollPane2.setViewportView(mensajeTA);

        redactarBtn.setText("Redactar mensaje");
        redactarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redactarBtnActionPerformed(evt);
            }
        });

        responderBtn.setText("Responder");
        responderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMensajeLayout = new javax.swing.GroupLayout(panelMensaje);
        panelMensaje.setLayout(panelMensajeLayout);
        panelMensajeLayout.setHorizontalGroup(
            panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelMensajeLayout.createSequentialGroup()
                        .addComponent(mensajeLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelMensajeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(redactarBtn)
                .addGap(73, 73, 73)
                .addComponent(responderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        panelMensajeLayout.setVerticalGroup(
            panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redactarBtn)
                    .addComponent(responderBtn))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRemitente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addComponent(panelRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void redactarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redactarBtnActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
        this.redactar = true;
        this.remitenteLabel.setText("Destinatario:");
        this.remitenteTF.setText("");
        this.remitenteTF.setEditable(true);
        this.fechaLabel.setVisible(false);
        this.fechaTF.setVisible(false);
        this.panelRespuesta.setSize(this.panelMensaje.getWidth(), this.panelMensaje.getHeight());
        this.panelRespuesta.setLocation(0, 0);
        this.panelMensaje.removeAll();
        this.panelMensaje.add(this.panelRespuesta);
        this.panelMensaje.revalidate();
        this.panelMensaje.repaint();
    }//GEN-LAST:event_redactarBtnActionPerformed

    private void responderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responderBtnActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
        if(this.seleccion != -1){
            this.panelMensaje.removeAll();
            this.panelRespuesta.setSize(this.panelMensaje.getWidth(), this.panelMensaje.getHeight());
            this.panelRespuesta.setLocation(0, 0);
            this.panelRespuesta.setDestinatario(this.mensajesRecibidos.get(this.seleccion).getIdRemitente());
            this.panelMensaje.add(this.panelRespuesta);
            this.panelMensaje.revalidate();
            this.panelMensaje.repaint();
        }else{
            JOptionPane.showMessageDialog(this, "Por favor seleccione un mensaje", "Mensaje no seleccionado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_responderBtnActionPerformed

    public long getDestinatario(){
        if(this.remitenteTF.getText().isEmpty())
            return -1;
        return Long.parseLong(this.remitenteTF.getText());
    }
    
    public boolean isRedactar(){
        return this.redactar;
    }
    
    public void reset(){
        this.redactar = false;
        this.remitenteLabel.setText("Remitente:");
        this.remitenteTF.setText(this.prevInfo);
        this.remitenteTF.setEditable(false);
        this.fechaLabel.setVisible(true);
        this.fechaTF.setVisible(true);
        this.panelMensaje.removeAll();
        this.panelMensaje.add(mensajeLabel);
        this.panelMensaje.add(jScrollPane2);
        this.panelMensaje.add(redactarBtn);
        this.panelMensaje.add(responderBtn);
        this.panelMensaje.revalidate();
        this.panelMensaje.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField fechaTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaMensajes;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JTextArea mensajeTA;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JLabel panelLabel;
    private javax.swing.JPanel panelLista;
    private javax.swing.JPanel panelMensaje;
    private javax.swing.JPanel panelRemitente;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JButton redactarBtn;
    private javax.swing.JLabel remitenteLabel;
    private javax.swing.JTextField remitenteTF;
    private javax.swing.JButton responderBtn;
    // End of variables declaration//GEN-END:variables
}
