/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Medico;
import Modelo.Mensaje;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Jorge
 */
public class CanalContactoAdmin extends javax.swing.JPanel {
    
    private EnviarMensaje panelRespuesta;
    private final ArrayList<Mensaje> mensajesRecibidos;
    private int seleccion = -1;

    /**
     * Creates new form CanalContactoAdmin
     */
    public CanalContactoAdmin() {
        initComponents();
        this.remitenteTF.setEditable(false);
        this.fechaTF.setEditable(false);
        this.mensajeTA.setEditable(false);
        this.panelRespuesta = new EnviarMensaje(Login.adm.getIdentificacion());
        this.panelRespuesta.setPanelAdmin(this);
        this.panelRespuesta.setBackground(this.panelMensaje.getBackground());
        this.mensajesRecibidos = new ArrayList<>();
        
        for(Mensaje msg: VentanaHome.Sistema_principal.getMensajesParaAdmin()){
            if(msg.getIdDestinatario() == Login.adm.getIdentificacion()){
                this.mensajesRecibidos.add(msg);
            }
        }
        
        String[] model = new String[this.mensajesRecibidos.size()];
        
        for(int i = 0; i < this.mensajesRecibidos.size(); i++){
            model[i] = Long.toString(this.mensajesRecibidos.get(i).getIdRemitente());
            //System.out.println(model[i]);
        }
        
        this.listaMensajes.setListData(model);
        
        this.listaMensajes.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                seleccion = listaMensajes.getSelectedIndex();
                Mensaje msg = mensajesRecibidos.get(seleccion);
                long idRemitente = msg.getIdRemitente();
                String nombreRemitente = "";
                Calendar fecha = msg.getFecha();
                String mensaje = msg.getMensaje();
                for(Medico m: VentanaHome.Sistema_principal.getMedicos()){
                    if(idRemitente == m.getIdentificacion()){
                        nombreRemitente = m.getNombre();
                        break;
                    }
                }
                remitenteTF.setText(nombreRemitente);
                fechaTF.setText(CitasPaciente.getTextoFecha(fecha));
                mensajeTA.setText(mensaje);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        panelMensajes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMensajes = new javax.swing.JList<>();
        panelMensaje = new javax.swing.JPanel();
        infoRemiPanel = new javax.swing.JPanel();
        remitenteLabel = new javax.swing.JLabel();
        remitenteTF = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        fechaTF = new javax.swing.JTextField();
        mensajeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mensajeTA = new javax.swing.JTextArea();
        responderBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 255));

        panelTitulo.setBackground(new java.awt.Color(204, 204, 255));
        panelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tituloLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Mensajes recibidos (Médicos)");
        tituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(tituloLabel)
                .addGap(222, 222, 222))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMensajes.setBackground(new java.awt.Color(204, 204, 255));
        panelMensajes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaMensajes.setBackground(new java.awt.Color(204, 204, 255));
        listaMensajes.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        listaMensajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaMensajes.setSelectionBackground(new java.awt.Color(102, 102, 255));
        listaMensajes.setVisibleRowCount(18);
        jScrollPane1.setViewportView(listaMensajes);

        javax.swing.GroupLayout panelMensajesLayout = new javax.swing.GroupLayout(panelMensajes);
        panelMensajes.setLayout(panelMensajesLayout);
        panelMensajesLayout.setHorizontalGroup(
            panelMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelMensajesLayout.setVerticalGroup(
            panelMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        panelMensaje.setBackground(new java.awt.Color(204, 204, 255));
        panelMensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        remitenteLabel.setText("Remitente:");

        fechaLabel.setText("Fecha:");

        javax.swing.GroupLayout infoRemiPanelLayout = new javax.swing.GroupLayout(infoRemiPanel);
        infoRemiPanel.setLayout(infoRemiPanelLayout);
        infoRemiPanelLayout.setHorizontalGroup(
            infoRemiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoRemiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(remitenteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remitenteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaTF)
                .addContainerGap())
        );
        infoRemiPanelLayout.setVerticalGroup(
            infoRemiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoRemiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoRemiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remitenteLabel)
                    .addComponent(remitenteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaLabel)
                    .addComponent(fechaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mensajeLabel.setText("Mensaje:");

        mensajeTA.setBackground(new java.awt.Color(204, 204, 255));
        mensajeTA.setColumns(20);
        mensajeTA.setLineWrap(true);
        mensajeTA.setRows(5);
        jScrollPane2.setViewportView(mensajeTA);

        responderBtn.setText("Responder");
        responderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMensajeLayout = new javax.swing.GroupLayout(panelMensaje);
        panelMensaje.setLayout(panelMensajeLayout);
        panelMensajeLayout.setHorizontalGroup(
            panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoRemiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMensajeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(responderBtn)
                .addGap(50, 50, 50))
            .addGroup(panelMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelMensajeLayout.createSequentialGroup()
                        .addComponent(mensajeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMensajeLayout.setVerticalGroup(
            panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeLayout.createSequentialGroup()
                .addComponent(infoRemiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensajeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(responderBtn)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void responderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responderBtnActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
        if(this.seleccion != -1){
            this.panelMensaje.removeAll();
            this.panelRespuesta.setSize(this.panelMensaje.getWidth(), this.panelMensaje.getHeight());
            this.panelRespuesta.setLocation(0, 0);
            this.panelRespuesta.setDestinatario(this.mensajesRecibidos.get(this.seleccion).getIdRemitente());
            this.panelMensaje.add(this.panelRespuesta);
            this.panelMensaje.revalidate();
            this.panelMensaje.repaint();
        }else{
            JOptionPane.showMessageDialog(this, "Por favor seleccione un mensaje", "Mensaje no seleccionado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_responderBtnActionPerformed

    public void reset(){
        this.panelMensaje.removeAll();
        this.panelMensaje.add(this.infoRemiPanel);
        this.panelMensaje.add(this.mensajeLabel);
        this.panelMensaje.add(this.jScrollPane2);
        this.panelMensaje.add(this.responderBtn);
        this.panelMensaje.revalidate();
        this.panelMensaje.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField fechaTF;
    private javax.swing.JPanel infoRemiPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaMensajes;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JTextArea mensajeTA;
    private javax.swing.JPanel panelMensaje;
    private javax.swing.JPanel panelMensajes;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel remitenteLabel;
    private javax.swing.JTextField remitenteTF;
    private javax.swing.JButton responderBtn;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
