/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Paciente;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 */
public class CitasPaciente extends javax.swing.JPanel {
    
    Paciente paciente;

    /**
     * Creates new form CitasPaciente
     * @param paciente
     */
    public CitasPaciente(Paciente paciente) {
        this.paciente = paciente;
        initComponents();
        
        //try{
            
        if(paciente != null && this.paciente.getCitasRegistradas().size()>0){
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < this.paciente.getCitasRegistradas().size(); i++){
                String fecha = getTextoFecha(this.paciente.getCitasRegistradas().get(i).getFecha());
                String especialidad = this.paciente.getCitasRegistradas().get(i).getEspecialidad();
                String medico = this.paciente.getCitasRegistradas().get(i).getMedico().getNombre();
                String lugar = this.paciente.getCitasRegistradas().get(i).getConsultorio().getSede();
                model.addRow(new Object[]{fecha, especialidad, medico, lugar});
            }
        }
        
        
       // }catch(Exception e){
            
        //}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPanel = new javax.swing.JLabel();
        tablaCitas = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        verDetallesB = new javax.swing.JButton();
        cancelarCitaB = new javax.swing.JButton();
        mensajeError = new javax.swing.JLabel();

        tituloPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanel.setText("Citas Asignadas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Especialidad", "Médico", "Lugar"
            }
        ));
        tablaCitas.setViewportView(jTable1);

        verDetallesB.setText("Ver detalles");
        verDetallesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDetallesBActionPerformed(evt);
            }
        });

        cancelarCitaB.setText("Cancelar cita");
        cancelarCitaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCitaBActionPerformed(evt);
            }
        });

        mensajeError.setText("Pruebas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(tituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tablaCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mensajeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verDetallesB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarCitaB)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tituloPanel)
                .addGap(28, 28, 28)
                .addComponent(tablaCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verDetallesB)
                    .addComponent(cancelarCitaB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensajeError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verDetallesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetallesBActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_verDetallesBActionPerformed

    private void cancelarCitaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCitaBActionPerformed
        // TODO add your handling code here:
        int seleccion = jTable1.getSelectedRow();
        if(seleccion != -1){
            boolean result = paciente.cancelarCita(paciente.getCitasRegistradas().get(seleccion).getFecha());
            int modelIndex = jTable1.convertRowIndexToModel(seleccion);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(modelIndex);
            if(result){
                mensajeError.setText("Cita cancelada");
            }else{
                mensajeError.setText("Error al cancelar la cita");
            }
        }else{
            mensajeError.setText("Por favor seleccione una cita");
        }
    }//GEN-LAST:event_cancelarCitaBActionPerformed

    public static String getTextoFecha(Calendar fecha){
        String res = "";
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int mes = fecha.get(Calendar.MONTH) + 1;
        int year = fecha.get(Calendar.YEAR);
        res += dia + "/" + mes + "/" + year;
        return res;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarCitaB;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JScrollPane tablaCitas;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JButton verDetallesB;
    // End of variables declaration//GEN-END:variables
}

