/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class Consultorios extends javax.swing.JPanel {
    
    private ListaConsultorios consPanel;
    private EditarConsultorio editarConsPanel;

    /**
     * Creates new form Consultorios
     */
    public Consultorios() {
        initComponents();
        this.consPanel = new ListaConsultorios();
        this.editarConsPanel = new EditarConsultorio();
        this.editarConsPanel.setParentPanel(this);
        this.consPanel.setLocation(0, 0);
        this.consPanel.setSize(500, 190);
        this.consPanel.inicializarLista();
        panelVariante.removeAll();
        panelVariante.add(this.consPanel);
        panelVariante.revalidate();
        panelVariante.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLabel = new javax.swing.JLabel();
        panelVariante = new javax.swing.JPanel();
        editarBtn = new javax.swing.JButton();
        instr1Label = new javax.swing.JLabel();
        instr2Label = new javax.swing.JLabel();

        panelLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelLabel.setText("Consultorios");

        javax.swing.GroupLayout panelVarianteLayout = new javax.swing.GroupLayout(panelVariante);
        panelVariante.setLayout(panelVarianteLayout);
        panelVarianteLayout.setHorizontalGroup(
            panelVarianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelVarianteLayout.setVerticalGroup(
            panelVarianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        instr1Label.setText("A continuación encontrará la lista de consultorios actualmente registrados en el sistema.");

        instr2Label.setText("En caso de querer modificar un registro seleccionelo y de click en \"Editar\".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarBtn)
                .addGap(228, 228, 228))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVariante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instr2Label)
                            .addComponent(instr1Label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(panelLabel)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLabel)
                .addGap(18, 18, 18)
                .addComponent(instr1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instr2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(panelVariante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        // TODO add your handling code here:
        int index = this.consPanel.getSelecccion();
        
        if(index != -1){
            this.editarConsPanel.setLocation(0, 0);
            this.editarConsPanel.setSize(500, 190);
            
            this.editarConsPanel.actualizarInfo(index);

            panelVariante.removeAll();
            panelVariante.add(this.editarConsPanel);
            panelVariante.revalidate();
            panelVariante.repaint();
            this.editarBtn.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Por favor seleccione un registro");
        }
    }//GEN-LAST:event_editarBtnActionPerformed

    public void actualizar(){
        this.consPanel.setLocation(0, 0);
        this.consPanel.setSize(500, 190);
        this.consPanel.actualizarLista();
        panelVariante.removeAll();
        panelVariante.add(this.consPanel);
        panelVariante.revalidate();
        panelVariante.repaint();
        this.editarBtn.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarBtn;
    private javax.swing.JLabel instr1Label;
    private javax.swing.JLabel instr2Label;
    private javax.swing.JLabel panelLabel;
    private javax.swing.JPanel panelVariante;
    // End of variables declaration//GEN-END:variables
}
