/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Consultorio;
import Modelo.Medico;
import Modelo.Sistema;
import static Vista.VentanaHome.Sistema_principal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class CrearCitas extends javax.swing.JPanel {
    
    Sistema sistema = Vista.VentanaHome.Sistema_principal;

    /**
     * Creates new form CrearCitas
     */
    public CrearCitas() {
        initComponents();
        Integer[] opciones = new Integer[31];
        for(int i = 0; i < 31; i++){
            opciones[i] = i + 1;
        }
        diaComboBox.setModel(new DefaultComboBoxModel<>(opciones));
        Sistema_principal.getConsultorios().add(new Consultorio(1, "C1", "Sede"));
        Sistema_principal.getConsultorios().add(new Consultorio(2, "C2", "Sede"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        tituloPanel = new javax.swing.JLabel();
        labelMes = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        labelYear = new javax.swing.JLabel();
        mesComboBox = new javax.swing.JComboBox<>();
        diaComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        diaRadioButton = new javax.swing.JRadioButton();
        semanaRadioButton = new javax.swing.JRadioButton();
        aceptarButton = new javax.swing.JButton();
        labelHora = new javax.swing.JLabel();
        horaComboBox = new javax.swing.JComboBox<>();
        labelEspecialidad = new javax.swing.JLabel();
        espComboBox = new javax.swing.JComboBox<>();
        labelMedico = new javax.swing.JLabel();
        medTextField = new javax.swing.JTextField();
        avisoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        tituloPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanel.setText("Creación de citas");

        labelMes.setText("Mes");

        labelDia.setText("Dia");

        labelYear.setText("Año");

        mesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mesComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mesComboBoxItemStateChanged(evt);
            }
        });
        mesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesComboBoxActionPerformed(evt);
            }
        });

        diaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaComboBoxActionPerformed(evt);
            }
        });

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));

        grupo.add(diaRadioButton);
        diaRadioButton.setText("Dia");

        grupo.add(semanaRadioButton);
        semanaRadioButton.setText("Semana");

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        labelHora.setText("Hora de inicio");

        horaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12", "14", "15", "16", "17", "18" }));

        labelEspecialidad.setText("Especialidad");

        espComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Alergología", "Anestesiología", "Cardiología", "Gastroenterología", "Endocrinología", "Epidemiología", "Geriatría", "Hepatología", "Hematología", "Infectología", "Medicina familiar y comunitaria", "Medicina física y rehabilitación", "Medicina intensiva", "Medicina interna", "Medicina preventiva y salud pública", "Nefrología", "Neumología", "Neurología", "Nutriología", "Oncología", "Pediatría", "Psiquiatría", "Reumatología", "Toxicología" }));

        labelMedico.setText("ID Médico");

        avisoLabel.setText("Ingrese los siguientes datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelMes)
                                    .addComponent(labelYear)
                                    .addComponent(labelDia, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEspecialidad)
                                    .addComponent(labelHora)
                                    .addComponent(labelMedico)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aceptarButton)
                                .addGap(8, 8, 8)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(avisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(semanaRadioButton))
                            .addComponent(tituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(tituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaRadioButton)
                    .addComponent(semanaRadioButton))
                .addGap(12, 12, 12)
                .addComponent(avisoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMes)
                            .addComponent(mesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDia)
                            .addComponent(diaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelYear)
                            .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHora)
                            .addComponent(horaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEspecialidad)
                            .addComponent(espComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMedico)
                            .addComponent(medTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addComponent(aceptarButton)
                .addGap(0, 67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void diaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaComboBoxActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
    }//GEN-LAST:event_diaComboBoxActionPerformed

    private void mesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesComboBoxActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
    }//GEN-LAST:event_mesComboBoxActionPerformed

    private void mesComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mesComboBoxItemStateChanged
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
        int dias;
        switch((String) mesComboBox.getSelectedItem()){
            case "Enero":
            case "Marzo":
            case "Mayo":
            case "Julio":
            case "Agosto":
            case "Octubre":
            case "Diciembre":
                dias = 31;
                break;
            case "Abril":
            case "Junio":
            case "Septiembre":
            case "Noviembre":
                dias = 30;
                break;
            default:
                dias = 28;
        }
        Integer[] opciones = new Integer[dias];
        for(int i = 0; i < dias; i++){
            opciones[i] = i + 1;
        }
        diaComboBox.setModel(new DefaultComboBoxModel<>(opciones));
    }//GEN-LAST:event_mesComboBoxItemStateChanged

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
        int dia = (int) (diaComboBox.getSelectedItem());
        int mes = mesEnt((String) mesComboBox.getSelectedItem());
        int year = Integer.parseInt((String) yearComboBox.getSelectedItem());
        int hora = Integer.parseInt((String) horaComboBox.getSelectedItem());
        String especialidad = (String) espComboBox.getSelectedItem();
        long idMedico = (medTextField.getText().equals("") || medTextField.getText() == null) ? -1 : (long) Integer.parseInt(medTextField.getText());
        if(diaRadioButton.isSelected()){
            if(idMedico == -1){
                Sistema.addCitasDia(dia, mes, year, hora, especialidad, Vista.VentanaHome.Sistema_principal);
            }else{
                Sistema.addCitasDia(dia, mes, year, hora, especialidad, idMedico, Vista.VentanaHome.Sistema_principal);
            }
        }else{
            if(idMedico == -1){
                Sistema.addCitasSemana(dia, diaSemana(dia, mes, year), mes, year, especialidad, Vista.VentanaHome.Sistema_principal);
            }else{
                Sistema.addCitasSemana(dia, diaSemana(dia, mes, year), mes, year, especialidad, idMedico, Vista.VentanaHome.Sistema_principal);
            }
        }
        JOptionPane.showMessageDialog(this, "Citas creadas exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aceptarButtonActionPerformed

    public int mesEnt(String mes){
        int res = 1;
        switch(mes){
            case "Enero":
                res = 1;
                break;
            case "Febrero":
                res = 2;
                break;
            case "Marzo":
                res = 3;
                break;
            case "Abril":
                res = 4;
                break;
            case "Mayo":
                res = 5;
                break;
            case "Junio":
                res = 6;
                break;
            case "Julio":
                res = 7;
                break;
            case "Agosto":
                res = 8;
                break;
            case "Septiembre":
                res = 9;
                break;
            case "Octubre":
                res = 10;
                break;
            case "Noviembre":
                res = 11;
                break;
            case "Diciembre":
                res = 12;
                break;
        }
        return res;
    }
    
    public int diaSemana(int dia, int mes, int year){
        Calendar fecha = new GregorianCalendar(year, mes - 1, dia);
        return fecha.get(Calendar.DAY_OF_WEEK);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JComboBox<Integer> diaComboBox;
    private javax.swing.JRadioButton diaRadioButton;
    private javax.swing.JComboBox<String> espComboBox;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JComboBox<String> horaComboBox;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelEspecialidad;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelMedico;
    private javax.swing.JLabel labelMes;
    private javax.swing.JLabel labelYear;
    private javax.swing.JTextField medTextField;
    private javax.swing.JComboBox<String> mesComboBox;
    private javax.swing.JRadioButton semanaRadioButton;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
