/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Consultorio;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class EditarConsultorio extends javax.swing.JPanel {
    
    private Consultorios parentPanel;
    private int index = -1;

    /**
     * Creates new form EditarConsultorio
     */
    public EditarConsultorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelarBtn = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();
        numeroLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        sedeLabel = new javax.swing.JLabel();
        numeroTF = new javax.swing.JTextField();
        nombreTF = new javax.swing.JTextField();
        sedeTF = new javax.swing.JTextField();

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        numeroLabel.setText("Número");

        nombreLabel.setText("Nombre");

        sedeLabel.setText("Sede");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(numeroLabel)
                                .addComponent(nombreLabel))
                            .addComponent(sedeLabel))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroTF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sedeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarBtn)
                        .addGap(42, 42, 42)
                        .addComponent(guardarBtn)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLabel)
                    .addComponent(numeroTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sedeLabel)
                    .addComponent(sedeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn)
                    .addComponent(guardarBtn))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        // TODO add your handling code here:
        String numero = this.numeroTF.getText();
        String nombre = this.nombreTF.getText();
        String sede = this.sedeTF.getText();
        boolean checkNum = numero.matches("[0-9]+");
        boolean checkNombre = !nombre.isEmpty();
        boolean checkSede = !sede.isEmpty();
        boolean checkAll = checkNum && checkNombre && checkSede;
        
        if(checkAll){
            VentanaHome.Sistema_principal.getConsultorios().get(index).setNumero(Integer.parseInt(numero));
            VentanaHome.Sistema_principal.getConsultorios().get(index).setNombre(nombre);
            VentanaHome.Sistema_principal.getConsultorios().get(index).setSede(sede);
            this.parentPanel.actualizar();
        }else{
            JOptionPane.showMessageDialog(this, "Por favor ingrese la información correctamente");
        }
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        this.parentPanel.actualizar();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    public void actualizarInfo(int index){
        this.index = index;
        Consultorio cons = VentanaHome.Sistema_principal.getConsultorios().get(index);
        this.numeroTF.setText(Integer.toString(cons.getNumero()));
        this.nombreTF.setText(cons.getNombre());
        this.sedeTF.setText(cons.getSede());
    }
    
    public void setParentPanel(Consultorios consultorios){
        this.parentPanel = consultorios;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField numeroTF;
    private javax.swing.JLabel sedeLabel;
    private javax.swing.JTextField sedeTF;
    // End of variables declaration//GEN-END:variables
}
