/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Paciente;
import Modelo.Sistema;
import static Modelo.Sistema.eliminar_paciente;
import static Modelo.Sistema.encontrar_paciente;

/**
 *
 * @author Alejandro Ortiz
 */
public class Eliminar_usuario extends javax.swing.JPanel {

    /**
     * Creates new form Eliminar_usuario
     */
    public Eliminar_usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF_documento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_info = new javax.swing.JTextArea();
        Ver_info = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        TF_estado = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar Usuarios");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Documento de usuario a eliminar");

        TF_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_documentoActionPerformed(evt);
            }
        });

        TA_info.setEditable(false);
        TA_info.setColumns(20);
        TA_info.setRows(5);
        jScrollPane1.setViewportView(TA_info);

        Ver_info.setText("Ver info del usuario");
        Ver_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_infoActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        TF_estado.setEditable(false);
        TF_estado.setBackground(new java.awt.Color(102, 204, 255));
        TF_estado.setForeground(new java.awt.Color(255, 255, 255));
        TF_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_estadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Eliminar)
                    .addComponent(jLabel2)
                    .addComponent(Ver_info))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TF_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TF_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ver_info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar))
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TF_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_documentoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        
        
        Sistema system = new Sistema();
        eliminar_paciente(Integer.valueOf(TF_documento.getText()), system);
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void TF_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_estadoActionPerformed

    private void Ver_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_infoActionPerformed
        // TODO add your handling code here:
        
        Paciente pac;
        Sistema system = new Sistema();
        
        pac = encontrar_paciente(Integer.valueOf(TF_documento.getText()),system);
        
        if(pac != null){    //SI HAY UN USUARIO CON LA CEDULA DADA SE MUESTRA LA INFO
        TA_info.setText(
        
            ("Nuevo usuario agregado\n" +
                "ID   " + pac.getIdentificacion() + "\n"+
                "Nombre   " + pac.getNombre() + "\n"+
                "Sexo   " + pac.getGenero() + "\n"+

                 //"Fecha de nacimiento  " + imprimir_horario(nacimiento) + //------------------------------------***************
                 "\n" )
            );
        }else{  //SI NO HAY COINCIDENCIA NO SE HACE NADA Y SE MUESTRA NOTIFICACION
            TA_info.setText("No hay coincidencias para el documento ingresado.");
        }
    }//GEN-LAST:event_Ver_infoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextArea TA_info;
    private javax.swing.JTextField TF_documento;
    private javax.swing.JTextField TF_estado;
    private javax.swing.JButton Ver_info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
