/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.*;
import java.awt.*;
import static Modelo.Sistema.encontrarPaciente;
import javax.swing.*;
/**
 *
 * @author USER
 */
public class historiaClinicaPaciente extends javax.swing.JPanel {

    private DefaultListModel model =  new DefaultListModel();
    private HistoriaClinica pacHistoriaClinica;
    /**
     * Creates new form historiaClinicaPaciente
     */
    public historiaClinicaPaciente() {
        
        initComponents();
        
        Paciente pac = Vista.Login.pac;
        
        Long doc =  pac.getIdentificacion();
        
        pac = encontrarPaciente(doc,Vista.VentanaHome.Sistema_principal);
        
        pacHistoriaClinica = pac.getHistoriaClinica();
        
        
        
        if(pacHistoriaClinica != null){
            for(String i:pacHistoriaClinica.getEnfermedades()){
                System.out.println(i);
                model.addElement(i);
            }
        } else {
            labelNullHistory.setText("No existe una historia clinica registrada");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        paneEnfermedades = new javax.swing.JScrollPane();
        listaEnfermedades = new javax.swing.JList<>();
        labelNullHistory = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));

        labelTitulo.setForeground(new java.awt.Color(0, 102, 0));
        labelTitulo.setText("Historia Clinica");

        listaEnfermedades.setBackground(new java.awt.Color(204, 255, 204));
        listaEnfermedades.setModel(model);
        paneEnfermedades.setViewportView(listaEnfermedades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(paneEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(labelNullHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(paneEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNullHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNullHistory;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JList<String> listaEnfermedades;
    private javax.swing.JScrollPane paneEnfermedades;
    // End of variables declaration//GEN-END:variables
}
