/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Consultorio;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 */
public class ListaConsultorios extends javax.swing.JPanel {
    
    /**
     * Creates new form ListaConsultorio
     */
    public ListaConsultorios() {
        initComponents();
        actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        consTable = new javax.swing.JTable();

        consTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Nombre", "Sede"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(consTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public int getSelecccion(){
        return this.consTable.getSelectedRow();
    }
    
    public void inicializarLista(){
        ArrayList<Consultorio> consultorios = VentanaHome.Sistema_principal.getConsultorios();
        DefaultTableModel model = (DefaultTableModel) this.consTable.getModel();
        for(Consultorio c: consultorios){
            int num = c.getNumero();
            String nombre = c.getNombre();
            String sede = c.getSede();
            model.addRow(new Object[]{num, nombre, sede});
        }
    }
    
    public void actualizarLista(){
        ArrayList<Consultorio> consultorios = VentanaHome.Sistema_principal.getConsultorios();
        DefaultTableModel model = (DefaultTableModel) this.consTable.getModel();
        for(int i = 0; i < model.getRowCount(); i++){
            int num = consultorios.get(i).getNumero();
            String nombre = consultorios.get(i).getNombre();
            String sede = consultorios.get(i).getSede();
            model.setValueAt(num, i, 0);
            model.setValueAt(nombre, i, 1);
            model.setValueAt(sede, i, 2);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable consTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
