/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Medico;
import Modelo.Paciente;
import Modelo.Sistema;
import static Modelo.Sistema.encontrarPaciente;
import static Modelo.Sistema.encontrarMedico;
import java.awt.BorderLayout;

/**
 *
 * @author Alejandro Ortiz
 */
public class Login extends javax.swing.JPanel {

    Sistema system;
    public static Paciente pac;
    public static Medico med;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PFClave = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        TFDocumento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TestLabel = new javax.swing.JLabel();
        BIngresar = new javax.swing.JButton();
        TFTest = new javax.swing.JTextField();
        CBRol = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Documento");

        jLabel2.setText("Contraseña");

        TFDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDocumentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Ingreso al sistema");

        TestLabel.setText("Pruebas");

        BIngresar.setText("Ingresar");
        BIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIngresarActionPerformed(evt);
            }
        });

        TFTest.setEditable(false);
        TFTest.setBackground(new java.awt.Color(0, 255, 153));
        TFTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTestActionPerformed(evt);
            }
        });

        CBRol.setBackground(new java.awt.Color(51, 102, 255));
        CBRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paciente", "Médico", "Administrador" }));
        CBRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBRolActionPerformed(evt);
            }
        });

        jLabel4.setText("Entrar como");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BIngresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFTest, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TFDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PFClave, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBRol, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PFClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BIngresar)
                    .addComponent(TFTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TestLabel)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        TestLabel.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void TFDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDocumentoActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
    }//GEN-LAST:event_TFDocumentoActionPerformed

    private void BIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIngresarActionPerformed
        
        VentanaHome.controlSesion.restart();
        String rol_sesion = CBRol.getSelectedItem().toString();

        String entrada = new String(PFClave.getPassword());
        TestLabel.setText(entrada);

        switch (rol_sesion){

            case "Paciente":
                pac = encontrarPaciente(Integer.valueOf(TFDocumento.getText()),Vista.VentanaHome.Sistema_principal);

                if(pac != null){
                   if( Modelo.Encriptacion.desencriptar(pac.getPassword()).equals(entrada)){    //14 de junio se agrego encriptado ---------------[]
                       TFTest.setText("Autenticado");

                        //Acceder seccion usuario
                        Panel_pacientes PR = new  Panel_pacientes();
                        PR.setSize(1000, 1000);
                        PR.setLocation(0,0);
                        Vista.VentanaHome.Panel_variante.removeAll();
                        Vista.VentanaHome.Panel_variante.add(PR,BorderLayout.CENTER);
                        Vista.VentanaHome.Panel_variante.revalidate();
                        Vista.VentanaHome.Panel_variante.repaint();

                   }else{
                       TFTest.setText("Intente de nuevo");    
                   }
               }else{
                   TFTest.setText("Usuario inexistente");
               }

                break;

            case "Médico":

                med = encontrarMedico(Integer.valueOf(TFDocumento.getText()),Vista.VentanaHome.Sistema_principal);

                if(med != null){
                   if(med.getPassword().equals(entrada)){
                       TFTest.setText("Autenticado");

                        //Acceder seccion usuario
                        PanelMedico PM = new  PanelMedico();
                        PM.setSize(1000, 1000);
                        PM.setLocation(0,0);
                        Vista.VentanaHome.Panel_variante.removeAll();
                        Vista.VentanaHome.Panel_variante.add(PM,BorderLayout.CENTER);
                        Vista.VentanaHome.Panel_variante.revalidate();
                        Vista.VentanaHome.Panel_variante.repaint();

                   }else{
                       TFTest.setText("Intente de nuevo");    
                   }
               }else{
                   TFTest.setText("Medico inexistente");
               }

                break;

            case "Administrador":

                break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BIngresarActionPerformed

    private void TFTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTestActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
    }//GEN-LAST:event_TFTestActionPerformed

    private void CBRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBRolActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
    }//GEN-LAST:event_CBRolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BIngresar;
    private javax.swing.JComboBox<String> CBRol;
    private javax.swing.JPasswordField PFClave;
    private javax.swing.JTextField TFDocumento;
    private javax.swing.JTextField TFTest;
    private javax.swing.JLabel TestLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
