/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.BorderLayout;

/**
 *
 * @author USER
 */
public class PanelMedico extends javax.swing.JPanel {

    /**
     * Creates new form PanelMedico
     */
    public PanelMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVariante = new javax.swing.JPanel();
        BTHorario = new javax.swing.JButton();
        B_mis_datos = new javax.swing.JButton();

        panelVariante.setBackground(new java.awt.Color(255, 204, 255));

        BTHorario.setText("Horario");
        BTHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTHorarioActionPerformed(evt);
            }
        });

        B_mis_datos.setText("Mis datos");
        B_mis_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_mis_datosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVarianteLayout = new javax.swing.GroupLayout(panelVariante);
        panelVariante.setLayout(panelVarianteLayout);
        panelVarianteLayout.setHorizontalGroup(
            panelVarianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVarianteLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(B_mis_datos)
                .addGap(39, 39, 39)
                .addComponent(BTHorario)
                .addContainerGap(536, Short.MAX_VALUE))
        );
        panelVarianteLayout.setVerticalGroup(
            panelVarianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVarianteLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(panelVarianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_mis_datos)
                    .addComponent(BTHorario))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVariante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVariante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTHorarioActionPerformed
        //Crear panel horario
        VentanaHome.controlSesion.restart();
        CitasMedico PR = new  CitasMedico(Vista.Login.med);
        PR.setSize(1000, 1000);
        PR.setLocation(0,0);
        panelVariante.removeAll();
        panelVariante.add(PR,BorderLayout.CENTER);
        panelVariante.revalidate();
        panelVariante.repaint(); 
    }//GEN-LAST:event_BTHorarioActionPerformed

    private void B_mis_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_mis_datosActionPerformed
        // TODO add your handling code here:
        VentanaHome.controlSesion.restart();
        panelDatosDoctor PR = new  panelDatosDoctor();
        PR.setSize(1000, 1000);
        PR.setLocation(0,0);
        panelVariante.removeAll();
        panelVariante.add(PR ,BorderLayout.CENTER);
        panelVariante.revalidate();
        panelVariante.repaint();
    }//GEN-LAST:event_B_mis_datosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTHorario;
    private javax.swing.JButton B_mis_datos;
    private javax.swing.JPanel panelVariante;
    // End of variables declaration//GEN-END:variables
}
