/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.Arrays;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Jorge
 */
public class PanelPrimerUsoCrearAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrimerUsoCrearAdmin
     */
    public PanelPrimerUsoCrearAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formTitle = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        confirmarLabel = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        fechaTF = new javax.swing.JTextField();
        instructionsText = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        confirmarTF = new javax.swing.JPasswordField();
        generoComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        formTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        formTitle.setText("Creación de la cuenta administrador");

        labelNombre.setText("Nombre");

        labelGenero.setText("Genero");

        labelFecha.setText("Fecha nacimiento");

        idLabel.setText("Identificación");

        passwordLabel.setText("Contraseña");

        confirmarLabel.setText("Confirmar contraseña");

        nombreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTFActionPerformed(evt);
            }
        });

        fechaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaTFActionPerformed(evt);
            }
        });

        instructionsText.setText("Por favor ingrese los siguientes datos, posteriormente de click en siguiente.");

        generoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));

        jLabel1.setText(" (DD/MM/AAAA)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(formTitle))
                    .addComponent(instructionsText)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombre)
                                    .addComponent(labelGenero))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelFecha)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(generoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreTF))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel)
                            .addComponent(passwordLabel)
                            .addComponent(confirmarLabel))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idTF, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(passwordTF)
                            .addComponent(confirmarTF))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(instructionsText)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre)
                    .addComponent(idLabel)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(labelGenero)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmarLabel)
                    .addComponent(labelFecha)
                    .addComponent(confirmarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFActionPerformed

    private void fechaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaTFActionPerformed
    
    public String getNombre(){
        return this.nombreTF.getText();
    }
    
    public String getGenero(){
        return (String) this.generoComboBox.getSelectedItem();
    }
    
    public Calendar getFechaNacimiento(){
        String fecha = this.fechaTF.getText();
        String[] datos = fecha.split("/");
        
        int dia = Integer.parseInt(datos[0]);
        int mes = Integer.parseInt(datos[1]);
        int year = Integer.parseInt(datos[2]);
        
        GregorianCalendar fechaObtenida = new GregorianCalendar(year, mes - 1, dia);
        
        return fechaObtenida;
    }
    
    public int getIdentificacion(){
        return Integer.parseInt(this.idTF.getText());
    }
    
    public String getPassword(){
        String password = "";
        for(char c: this.passwordTF.getPassword())
            password += c;
        return password;
    }
    
    public String getConfirmarPassword(){
        String confirmar = "";
        for(char c: this.confirmarTF.getPassword())
            confirmar += c;
        return confirmar;
    }
    
    public boolean confirmarInformacion(){
        boolean nombreIsCorrect = !this.nombreTF.getText().isEmpty();
        String genero = (String) this.generoComboBox.getSelectedItem();
        boolean generoIsCorrect = !genero.isEmpty();
        boolean fechaIsCorrect = this.fechaTF.getText().matches("\\d{2}/\\d{2}/\\d{4}");
        boolean idIsCorrect = this.idTF.getText().matches("[0-9]+");
        String password = getPassword();
        String confirmar = getConfirmarPassword();
        boolean passwordIsCorrect = !password.isEmpty() && password.equals(confirmar);
        
        return nombreIsCorrect && generoIsCorrect && fechaIsCorrect && idIsCorrect && passwordIsCorrect;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmarLabel;
    private javax.swing.JPasswordField confirmarTF;
    private javax.swing.JTextField fechaTF;
    private javax.swing.JLabel formTitle;
    private javax.swing.JComboBox<String> generoComboBox;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel instructionsText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTF;
    // End of variables declaration//GEN-END:variables
}
