/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Jorge
 */
public class PanelPrimerUsoCrearPaciente extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrimerUsoCrearPaciente
     */
    public PanelPrimerUsoCrearPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLabel = new javax.swing.JLabel();
        instrLabel = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        generoComboBox = new javax.swing.JComboBox<>();
        fechaTF = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        generoLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        confirmarLabel = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        confirmarTF = new javax.swing.JPasswordField();
        passwordTF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        panelLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelLabel.setText("Creación Paciente");

        instrLabel.setText("Por favor ingrese los siguientes datos, posteriormente de click en siguiente.");

        generoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));

        nombreLabel.setText("Nombre");

        generoLabel.setText("Género");

        fechaLabel.setText("Fecha nacimiento");

        idLabel.setText("Identificación");

        passwordLabel.setText("Contraseña");

        confirmarLabel.setText("Confirmar contraseña");

        jLabel1.setText("DD/MM/AAAA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(panelLabel)
                .addGap(246, 246, 246))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLabel)
                            .addComponent(generoLabel)
                            .addComponent(fechaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel)
                            .addComponent(confirmarLabel)
                            .addComponent(passwordLabel))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idTF, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(passwordTF)
                            .addComponent(confirmarTF)))
                    .addComponent(instrLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLabel)
                .addGap(26, 26, 26)
                .addComponent(instrLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel)
                    .addComponent(idLabel)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoLabel)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaLabel)
                    .addComponent(confirmarLabel)
                    .addComponent(confirmarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getNombre(){
        return this.nombreTF.getText();
    }
    
    public String getGenero(){
        return (String) this.generoComboBox.getSelectedItem();
    }
    
    public Calendar getFechaNacimiento(){
        String fecha = this.fechaTF.getText();
        String[] datos = fecha.split("/");
        
        int dia = Integer.parseInt(datos[0]);
        int mes = Integer.parseInt(datos[1]);
        int year = Integer.parseInt(datos[2]);
        
        GregorianCalendar fechaObtenida = new GregorianCalendar(year, mes - 1, dia);
        
        return fechaObtenida;
    }
    
    public long getIdentificacion(){
        return Long.parseLong(this.idTF.getText());
    }
    
    public String getPassword(){
        String password = "";
        for(char c: this.passwordTF.getPassword())
            password += c;
        return password;
    }
    
    public String getPasswordEncrypted(){
        return Modelo.Encriptacion.encriptar(getPassword());
    }
    
    public String getConfirmarPassword(){
        String confirmar = "";
        for(char c: this.confirmarTF.getPassword())
            confirmar += c;
        return confirmar;
    }
    
    public boolean confirmarInformacion(){
        boolean nombreIsCorrect = !this.nombreTF.getText().isEmpty();
        String genero = (String) this.generoComboBox.getSelectedItem();
        boolean generoIsCorrect = !genero.isEmpty();
        boolean fechaIsCorrect = this.fechaTF.getText().matches("\\d{2}/\\d{2}/\\d{4}");
        boolean idIsCorrect = this.idTF.getText().matches("[0-9]+");
        String password = getPassword();
        String confirmar = getConfirmarPassword();
        boolean passwordIsCorrect = !password.isEmpty() && password.equals(confirmar);
        
        return nombreIsCorrect && generoIsCorrect && fechaIsCorrect && idIsCorrect && passwordIsCorrect;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmarLabel;
    private javax.swing.JPasswordField confirmarTF;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField fechaTF;
    private javax.swing.JComboBox<String> generoComboBox;
    private javax.swing.JLabel generoLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel instrLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JLabel panelLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTF;
    // End of variables declaration//GEN-END:variables
}
