/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ContactoPaciente;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import Modelo.Paciente;
import Modelo.Sistema;
import static Modelo.Sistema.encontrarPaciente;

/**
 *
 * @author Alejandro Ortiz
 */
public class panelDatosUsuario extends javax.swing.JPanel {
    
    //Sistema system = Vista.VentanaHome.Sistema_principal;
    //Atributos a leer.
    int documento;
    String nombre;
    String sexo;
    String clave; 
    GregorianCalendar nacimiento;
    
    Calendar fecha_actual = Calendar.getInstance();
            
   

    /**
     * Creates new form NuevoUsuario
     */
    public panelDatosUsuario() {
        initComponents();
        
        
        
                
        Paciente pac = Vista.Login.pac;
        //Sistema system = new Sistema();
        
        Long doc =  pac.getIdentificacion();
        
        pac = encontrarPaciente(doc,Vista.VentanaHome.Sistema_principal);
        
        if(pac != null){    //SI HAY UN USUARIO CON LA CEDULA DADA SE MUESTRA LA INFO
            
            TF_documento.setText("" + pac.getIdentificacion());
            TF_nombre.setText("" + pac.getNombre());
            TF_sexo.setText(pac.getGenero());  
            TF_nacimiento.setText("" + imprimir_horarioMD((GregorianCalendar)pac.getFechaNacimiento()) );
            
            
            
            
            if(pac.getContactoPaciente() != null){
                TF_direccion.setText(pac.getContactoPaciente().direccion);
                TF_telefono.setText(pac.getContactoPaciente().telefono);
                TF_email.setText(pac.getContactoPaciente().email);
                TF_cnombre.setText(pac.getContactoPaciente().cnombre);
                TF_cvinculo.setText(pac.getContactoPaciente().cvinculo);
                TF_ctelefono.setText(pac.getContactoPaciente().ctelefono);
                
                
            }
            

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_documento = new javax.swing.JTextField();
        TF_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TF_sexo = new javax.swing.JTextField();
        TF_nacimiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TF_direccion = new javax.swing.JTextField();
        TF_telefono = new javax.swing.JTextField();
        TF_email = new javax.swing.JTextField();
        TF_cnombre = new javax.swing.JTextField();
        TF_ctelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TF_cvinculo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        B_actualizar = new javax.swing.JButton();
        L_estado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Documento");

        jLabel2.setText("Nombre");

        jLabel3.setText("Sexo");

        jLabel4.setText("Fecha de nacimiento");

        TF_documento.setEditable(false);
        TF_documento.setBackground(new java.awt.Color(153, 204, 255));
        TF_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_documentoActionPerformed(evt);
            }
        });

        TF_nombre.setEditable(false);
        TF_nombre.setBackground(new java.awt.Color(153, 204, 255));
        TF_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_nombreActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Mis datos");

        TF_sexo.setEditable(false);
        TF_sexo.setBackground(new java.awt.Color(153, 204, 255));
        TF_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_sexoActionPerformed(evt);
            }
        });

        TF_nacimiento.setEditable(false);
        TF_nacimiento.setBackground(new java.awt.Color(153, 204, 255));
        TF_nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_nacimientoActionPerformed(evt);
            }
        });

        jLabel7.setText("E-mail");

        jLabel8.setText("Teléfono");

        jLabel9.setText("Persona de contacto");

        jLabel10.setText("Dirección de Residencia");

        TF_cnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_cnombreActionPerformed(evt);
            }
        });

        jLabel11.setText("Nombre");

        jLabel12.setText("Teléfono");

        TF_cvinculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_cvinculoActionPerformed(evt);
            }
        });

        jLabel13.setText("Parentesco o vínculo");

        jLabel14.setFont(new java.awt.Font("Futura Md BT", 0, 24)); // NOI18N
        jLabel14.setText("Datos de contacto");

        jLabel15.setFont(new java.awt.Font("Futura Md BT", 0, 24)); // NOI18N
        jLabel15.setText("Datos Personales");

        B_actualizar.setText("Actualizar");
        B_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_actualizarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html> De hallar cualquier inconsistencia o error, puede notificarlo al correo xyz.com. Adjunte los soportes pertinentes. </html>");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel10)))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_direccion)
                            .addComponent(TF_telefono)
                            .addComponent(TF_email, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_ctelefono)
                                    .addComponent(TF_cnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(TF_cvinculo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(B_actualizar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TF_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TF_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(jLabel14)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TF_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_cnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(TF_cvinculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_ctelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(8, 8, 8)
                .addComponent(B_actualizar)
                .addGap(18, 18, 18)
                .addComponent(L_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TF_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_nombreActionPerformed

    private void TF_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_documentoActionPerformed

    private void TF_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_sexoActionPerformed

    private void TF_nacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_nacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_nacimientoActionPerformed

    private void TF_cnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_cnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_cnombreActionPerformed

    private void TF_cvinculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_cvinculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_cvinculoActionPerformed

    private void B_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_actualizarActionPerformed
        // TODO add your handling code here:
        
        try{
        String direccion = TF_direccion.getText();
        String telefono = TF_telefono.getText();
        String email = TF_email.getText();
        String cnombre = TF_cnombre.getText();
        String cvinculo = TF_cvinculo.getText();
        String ctelefono = TF_ctelefono.getText();
        
        
        
        
        ContactoPaciente Datos_contacto_paciente = new ContactoPaciente (direccion,telefono,email, cnombre, cvinculo,  ctelefono);
        Vista.Login.pac.setContactoPaciente(Datos_contacto_paciente);
            L_estado.setText("Datos actualizados con exito");
        }catch(Exception e){
            L_estado.setText("Ha ocurrido un error, por favor \n  verifique los datos ingresados");
        }
        
        //SET EL PACIENTE CON LOS DATOS LEIDOS
        
    }//GEN-LAST:event_B_actualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_actualizar;
    private javax.swing.JLabel L_estado;
    private javax.swing.JTextField TF_cnombre;
    private javax.swing.JTextField TF_ctelefono;
    private javax.swing.JTextField TF_cvinculo;
    private javax.swing.JTextField TF_direccion;
    private javax.swing.JTextField TF_documento;
    private javax.swing.JTextField TF_email;
    private javax.swing.JTextField TF_nacimiento;
    private javax.swing.JTextField TF_nombre;
    private javax.swing.JTextField TF_sexo;
    private javax.swing.JTextField TF_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables








    //year, month,dayOfMonth,hourOfDay, minute)
    public static GregorianCalendar crear_horario(int year,int month_1_12,int dayOfMonth,int hourOfDay24h,int minute){
        
        GregorianCalendar horario = new GregorianCalendar(year, month_1_12 - 1,dayOfMonth,hourOfDay24h, minute);
        return horario;
    }
    
    //Mes en la clase calendar va de 0 a 11,resulta mas intuitivo usar 1 a 12,a esto se deben los +1 y -1
    
    
    
    public boolean fecha_futura(Calendar fecha){
        
        boolean r = false;
        
        if(fecha_actual.get(Calendar.YEAR)<fecha.get(Calendar.YEAR) ||
           ( fecha_actual.get(Calendar.YEAR) == fecha.get(Calendar.YEAR) && fecha_actual.get(Calendar.MONTH)< fecha.get(Calendar.MONTH) ) ||
                
           (    ( fecha_actual.get(Calendar.YEAR) == fecha.get(Calendar.YEAR) && fecha_actual.get(Calendar.MONTH)== fecha.get(Calendar.MONTH) ) &&
           fecha_actual.get(Calendar.DAY_OF_MONTH)<fecha.get(Calendar.DAY_OF_MONTH))   ){
            
            r = true;
        }
        
        return r;
    }
    
    public String imprimir_horarioMD(GregorianCalendar horario){
        int year = horario.get(Calendar.YEAR);
        int mes = horario.get(Calendar.MONTH) + 1 ; 
        int dia = horario.get(Calendar.DAY_OF_MONTH); 
        int hora = horario.get(Calendar.HOUR_OF_DAY);
        int minuto = horario.get(Calendar.MINUTE);
        
        return  "[ Año: " + year + " / Mes: " + mes + " / Día: " + dia 
                //+ " / " + hora + " : " + minuto 
                + " ]" ;
    }

    public int switch_mes(String mes){
        int r = 1;
        
        switch (mes){
            
            case "Enero":
                r = 1;
                break;
                
            case "Febrero":
                r = 2;
                break;
                
            case "Marzo":
                r = 3;
                break;
                
            case "Abril":
                r = 4;
                break;
                
            case "Mayo":
                r = 5;
                break;
                
            case "Junio":
                r = 6;
                break;
                
            case "Julio":
                r = 7;
                break;
                
            case "Agosto":
                r = 8;
                break;
                
            case "Septiembre":
                r = 9;
                break;
                
            case "Octubre":
                r = 10;
                break;
                
            case "Noviembre":
                r = 11;
                break;
                
            case "Diciembre":
                r = 12;
                break;
                
        }
        
        return r;
    }




}
