/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.BorderLayout;

/**
 *
 * @author USER
 */
public class PanelMedico extends javax.swing.JPanel {

    /**
     * Creates new form PanelMedico
     */
    public PanelMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVariante = new javax.swing.JPanel();
        BTHorario = new javax.swing.JButton();

        BTHorario.setText("Horario");
        BTHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVarianteLayout = new javax.swing.GroupLayout(panelVariante);
        panelVariante.setLayout(panelVarianteLayout);
        panelVarianteLayout.setHorizontalGroup(
            panelVarianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVarianteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(BTHorario)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        panelVarianteLayout.setVerticalGroup(
            panelVarianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVarianteLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(BTHorario)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVariante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVariante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTHorarioActionPerformed
        //Crear panel horario
        VentanaHome.controlSesion.restart();
        CitasMedico PR = new  CitasMedico(Vista.Login.med);
        PR.setSize(1000, 1000);
        PR.setLocation(0,0);
        panelVariante.removeAll();
        panelVariante.add(PR,BorderLayout.CENTER);
        panelVariante.revalidate();
        panelVariante.repaint(); 
    }//GEN-LAST:event_BTHorarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTHorario;
    private javax.swing.JPanel panelVariante;
    // End of variables declaration//GEN-END:variables
}
