/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Falla;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 */
public class ReporteFallasAdmin extends javax.swing.JPanel {

    /**
     * Creates new form ReporteFallasAdmin
     */
    public ReporteFallasAdmin() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) this.fallasTable.getModel();
        for(Falla f: VentanaHome.Sistema_principal.getFallas()){
            String fecha = CitasPaciente.getTextoFecha(f.getFecha());
            String usuario = Long.toString(f.getUsuario().getIdentificacion());
            String componente = f.getComponente();
            model.addRow(new Object[]{fecha, usuario, componente});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLabel = new javax.swing.JLabel();
        intrLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fallasTable = new javax.swing.JTable();
        detallesBtn = new javax.swing.JButton();

        panelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panelLabel.setText("Reporte de fallas");

        intrLabel.setText("A continuación se encuentran las diferentes fallas registradas por los usuarios.");

        fallasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Usuario", "Componente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(fallasTable);

        detallesBtn.setText("Ver detalles");
        detallesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(panelLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intrLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(detallesBtn)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelLabel)
                .addGap(27, 27, 27)
                .addComponent(intrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detallesBtn)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detallesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallesBtnActionPerformed
        // TODO add your handling code here:
        int seleccion = this.fallasTable.getSelectedRow();
        if(seleccion != -1){
            Falla falla = VentanaHome.Sistema_principal.getFallas().get(seleccion);
            long idUsuario = falla.getUsuario().getIdentificacion();
            String nombreUsuario = falla.getUsuario().getNombre();
            String descripcion = falla.getDescripcion();
            String reporte = "ID Usuario: " + idUsuario + "\n"
                            + "Nombre usuario: " + nombreUsuario + "\n"
                            + "Descripción:" + descripcion;
            JTextArea textArea = new JTextArea();
            textArea.setLineWrap(true);
            textArea.setText(reporte);
            textArea.setEditable(false);
            JOptionPane.showMessageDialog(this, textArea, "Fecha: " + CitasPaciente.getTextoFecha(falla.getFecha()), JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Por favor seleccione un registro");
        }
    }//GEN-LAST:event_detallesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detallesBtn;
    private javax.swing.JTable fallasTable;
    private javax.swing.JLabel intrLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel panelLabel;
    // End of variables declaration//GEN-END:variables
}
