/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Falla;
import Modelo.Paciente;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class ReportarFallaPaciente extends javax.swing.JPanel {

    private Panel_pacientes parentPanel;
    
    /**
     * Creates new form ReportarFallaPaciente
     */
    public ReportarFallaPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLabel = new javax.swing.JLabel();
        instrLabel1 = new javax.swing.JLabel();
        instrLabel2 = new javax.swing.JLabel();
        compLabel = new javax.swing.JLabel();
        compComboBox = new javax.swing.JComboBox<>();
        descLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTA = new javax.swing.JTextArea();
        cancelarBtn = new javax.swing.JButton();
        registrarBtn = new javax.swing.JButton();

        panelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panelLabel.setText("Reportar una falla");

        instrLabel1.setText("Por favor ingrese la siguiente información. Posteriormente de click en \"Registrar\".");

        instrLabel2.setText("El equipo de desarrollo intentará solucionar el problema lo más pronto posible.");

        compLabel.setText("Componente");

        compComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inicio de sesión", "Buscador de citas", "Lista de citas asignadas", "Información de la cuenta" }));

        descLabel.setText("Descripción");

        descTA.setColumns(20);
        descTA.setLineWrap(true);
        descTA.setRows(5);
        jScrollPane1.setViewportView(descTA);

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        registrarBtn.setText("Registrar");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(panelLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instrLabel1)
                            .addComponent(instrLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(compLabel)
                                .addGap(42, 42, 42)
                                .addComponent(compComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(cancelarBtn)
                        .addGap(111, 111, 111)
                        .addComponent(registrarBtn)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelLabel)
                .addGap(26, 26, 26)
                .addComponent(instrLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instrLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compLabel)
                    .addComponent(compComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(descLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn)
                    .addComponent(registrarBtn))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        this.parentPanel.reset();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        // TODO add your handling code here:
        Calendar dateNow = Calendar.getInstance();
        Paciente paciente = Vista.Login.pac;
        String componente = (String) this.compComboBox.getSelectedItem();
        String descripcion = "";
        try{
            descripcion = this.descTA.getText();
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "Por favor ingrese la información correctamente");
        }
        boolean descIsCorrect = !descripcion.isEmpty();
        
        if(descIsCorrect){
            Falla falla = new Falla(dateNow, paciente, componente, descripcion);
            VentanaHome.Sistema_principal.getFallas().add(falla);
            this.parentPanel.reset();
            JOptionPane.showMessageDialog(this, "Falla registrada correctamente");
        }else{
            JOptionPane.showMessageDialog(this, "Por favor ingrese la información correctamente");
        }
    }//GEN-LAST:event_registrarBtnActionPerformed

    public void setParentPanel(Panel_pacientes panel){
        this.parentPanel = panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JComboBox<String> compComboBox;
    private javax.swing.JLabel compLabel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextArea descTA;
    private javax.swing.JLabel instrLabel1;
    private javax.swing.JLabel instrLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel panelLabel;
    private javax.swing.JButton registrarBtn;
    // End of variables declaration//GEN-END:variables
}
